spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patagonian_students?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 261997
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
